scrape_configs:
  - job_name: grok
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['grok:9144']
  - job_name: cratedb-adapter
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['cratedb-adapter:9268']
remote_write:
   - url: http://cratedb-adapter:9268/write
remote_read:
   - url: http://cratedb-adapter:9268/read